In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats
from scipy.stats import norm
from scipy.stats import bootstrap

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import GradientBoostingRegressor


In [34]:
df = pd.read_excel("Data_Predictive_Models.xlsx", sheet_name = "Data_Predictive_Models")
# df

## Process indicators (separate responses):

In [45]:
Y = df.iloc[:,[25]]
X = df.iloc[:,1:24]
Y

NS
0   7.284552e+05
1   7.304067e+05
2   1.332367e+06
3   1.120701e+06
4   6.907727e+05
5   1.205736e+06
6   6.221503e+05
7   7.103217e+05
8   7.402124e+05
9   6.015154e+05
10  7.421989e+05
11  5.060789e+05
12  5.264930e+05
13  7.654479e+05
14  9.677078e+05
15  2.163590e+05
16  8.827033e+05
17  1.060082e+06
18  5.779487e+05
19  1.264609e+06
20  8.530081e+05
21  8.420256e+05
22  8.269086e+05
23  9.698359e+05
24  9.121351e+05
25  1.037348e+06
26  1.284036e+06
27  1.076969e+06
28  1.038604e+06
29  1.076229e+06
30  8.179790e+05
31  9.831301e+05
32  9.231783e+05
33  1.015414e+06
34  1.106287e+06
35  6.171585e+05
36  1.085896e+06
37  1.022012e+06
38  1.497733e+06
39  1.403447e+06
40  1.438191e+06
41  1.604156e+06
42  1.112992e+06
43  1.429285e+06
44  1.134213e+06
45  1.177913e+06
46  1.106375e+06
47  1.286561e+06
48  1.165945e+06
49  1.138028e+06

In [46]:
X_scaler = MinMaxScaler().fit(X)
Y_scaler = MinMaxScaler().fit(Y)
X_scaled = X_scaler.transform(X)
Y_scaled = Y_scaler.transform(Y)
Y_scaled

array([[0.36899927],
       [0.37040544],
       [0.80415777],
       [0.65163839],
       [0.34184653],
       [0.71291198],
       [0.29239954],
       [0.35593289],
       [0.37747114],
       [0.27753069],
       [0.37890255],
       [0.20876236],
       [0.22347211],
       [0.39565497],
       [0.54139668],
       [0.        ],
       [0.4801453 ],
       [0.60795816],
       [0.26054933],
       [0.75533376],
       [0.45874788],
       [0.45083426],
       [0.43994148],
       [0.54293012],
       [0.50135285],
       [0.59157731],
       [0.76933185],
       [0.6201266 ],
       [0.59248242],
       [0.61959313],
       [0.43350711],
       [0.55250945],
       [0.5093102 ],
       [0.57577222],
       [0.6412524 ],
       [0.28880264],
       [0.62655931],
       [0.58052635],
       [0.92331531],
       [0.8553757 ],
       [0.88041117],
       [1.        ],
       [0.64608339],
       [0.87399402],
       [0.66137483],
       [0.69286314],
       [0.64131582],
       [0.771

In [47]:
X = X_scaled
Y = Y_scaled

In [48]:
Y = np.array(Y)
X = np.array(X)

In [49]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=47) # 80% training and 20% test

print(y_train.shape)
y_train = y_train.reshape((len(y_train),))
print(y_train.shape)
y_test = y_test.reshape((len(y_test),))

(40, 1)
(40,)


In [50]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.datasets import make_regression

# X, y = make_regression(n_features=22)
regr = GradientBoostingRegressor(learning_rate=0.1, n_estimators=100, subsample=1.0, 
                                 criterion='friedman_mse', min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
                                 max_depth=3, min_impurity_decrease=0.0)
regr.fit(X_train, y_train)
# regr.predict()
y_pred = regr.predict(X_test)
y_pred.shape
y_pred = y_pred.reshape(-1,1)
y_pred.shape

y_test = y_test.reshape(-1,1)
y_test.shape

(10, 1)

In [51]:
y_pred

array([[0.71853136],
       [0.67545917],
       [0.51191507],
       [0.683055  ],
       [0.52812721],
       [0.7585663 ],
       [0.78208609],
       [0.64223958],
       [0.30235128],
       [0.75990452]])

In [52]:
ss = regr.score(X_test, y_test, sample_weight=None)
ss

-0.22320974542789185

## People Indicators

In [111]:
# Prediction for "TR":

Y = df.iloc[:,[37]]
X = df.iloc[:,26:35]
Y = np.array(Y).astype("float16")
X = np.array(X).astype("float16")
Y

array([[10.   ],
       [ 8.   ],
       [ 5.   ],
       [ 6.   ],
       [ 5.   ],
       [ 7.   ],
       [11.   ],
       [10.   ],
       [11.   ],
       [ 6.   ],
       [ 8.   ],
       [11.   ],
       [12.   ],
       [ 7.   ],
       [ 5.   ],
       [ 7.   ],
       [ 7.   ],
       [ 9.   ],
       [ 6.   ],
       [10.   ],
       [11.   ],
       [ 6.   ],
       [ 5.   ],
       [11.   ],
       [ 9.   ],
       [10.   ],
       [ 8.   ],
       [ 8.   ],
       [ 6.   ],
       [ 7.   ],
       [ 7.55 ],
       [ 6.895],
       [ 8.46 ],
       [10.03 ],
       [ 9.87 ],
       [ 8.66 ],
       [12.8  ],
       [ 8.49 ],
       [10.6  ],
       [ 9.33 ],
       [ 7.293],
       [ 6.914],
       [ 7.605],
       [12.05 ],
       [ 7.812],
       [ 9.375],
       [ 8.805],
       [ 5.54 ],
       [13.02 ],
       [ 9.61 ]], dtype=float16)

In [112]:
X_scaler = MinMaxScaler().fit(X)
Y_scaler = MinMaxScaler().fit(Y)
X_scaled = X_scaler.transform(X)
Y_scaled = Y_scaler.transform(Y)
Y_scaled

X = X_scaled
Y = Y_scaled

In [113]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=47) # 80% training and 20% test

print(y_train.shape)
y_train = y_train.reshape((len(y_train),))
print(y_train.shape)
y_test = y_test.reshape((len(y_test),))

(40, 1)
(40,)


In [114]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

# X, y = make_regression(n_features=9)
regr = GradientBoostingRegressor(learning_rate=0.1, n_estimators=400, subsample=1.0, 
                                 criterion='friedman_mse', min_samples_split=2, min_samples_leaf=5, min_weight_fraction_leaf=0.0, 
                                 max_depth=8, min_impurity_decrease=0.0)
regr.fit(X_train, y_train)
# regr.predict()
y_pred = regr.predict(X_test)
y_pred.shape
y_pred = y_pred.reshape(-1,1)
y_pred.shape

y_test = y_test.reshape(-1,1)
y_test.shape

(10, 1)

In [115]:
y_pred

array([[0.40428201],
       [0.19787199],
       [0.17882856],
       [0.68740547],
       [0.26495144],
       [0.70646047],
       [0.30017663],
       [0.39266097],
       [0.44846282],
       [0.43095338]])

In [116]:
ss = regr.score(X_test, y_test, sample_weight=None)
ss

-0.9557252302724032

In [117]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-0.9557252302724033