In [1]:
# Bootstrapping_data

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats
from scipy.stats import norm
from scipy.stats import bootstrap

In [2]:
df = pd.read_excel("Data_Treatment - Great_Lakes.xlsx", sheet_name = "Compiled_Data")
# df

# df = df.drop(["Dates"], axis = 1)
heads = df.columns.to_list()
# heads

In [10]:
df = df.fillna(method="backfill")

In [11]:
df.head(100)

Month         BRH     MO  RPO  RCO     WIP    WS   WRA       BOTH  \
0  2019-01-01  16076.8300   86.0  216   58     8.0   3.0  10.0   182.5100   
1  2019-02-01  16345.9000   86.0  242   68     8.0   3.0  10.0    33.8700   
2  2019-03-01  17658.4200   86.0  378  120     8.0   3.0  10.0   592.1200   
3  2019-04-01  17683.9300   86.0  406    0     8.0   3.0  10.0  1540.2200   
4  2019-05-01  21552.3400   86.0  414    0     8.0   3.0  10.0  1874.6000   
5  2019-06-01  16620.9900   86.0  328    0     8.0   3.0  10.0  1379.5900   
6  2019-07-01  20494.8900   86.0  267    0     8.0   3.0  10.0   533.2900   
7  2019-08-01  16428.8200   86.0  335    0     8.0   3.0  10.0    69.1300   
8  2019-09-01  15284.3300   86.0  253    0     8.0   3.0  10.0    10.7500   
9  2019-10-01  19306.1800   86.0  336    0     8.0   3.0  10.0    47.5000   
10 2019-11-01  15374.6500   86.0  252    0     8.0   3.0  10.0    23.7500   
11 2019-12-01  15115.3800   86.0  193    0     8.0   3.0  10.0   224.7800   
12 2020-01-01  12012.1800   86.0  239    0     8.0   3.0  10.0    56.2500   
13 2020-02-01  14833.4500   86.0  219    0     8.0  18.0   5.0   113.8000   
14 2020-03-01  15756.5700   86.0    0    0     8.0  24.0   4.0   890.1800   
15 2020-04-01  11298.9400   86.0  221    0     8.0  26.0   8.0    37.5000   
16 2020-05-01   9620.2200   86.0  139    0     8.0  32.0  11.0     5.5000   
17 2020-06-01  12547.4200   86.0  269    0     8.0  65.0  19.0  1609.9800   
18 2020-07-01  18121.7500   86.0  376    0     8.0  49.0   6.0  2749.3500   
19 2020-08-01  14517.1400   86.0  305    0     8.0  48.0  10.0  1737.3600   
20 2020-09-01  14601.2000   86.0  300    0     8.0  38.0   3.0  1932.8600   
21 2020-10-01  18724.3700   86.0   97    0     8.0  29.0   9.0  1390.0300   
22 2020-11-01  14864.6100   86.0    0    0     8.0  32.0   2.0  1816.5600   
23 2020-12-01  15527.0600   86.0    0    0     8.0  19.0   0.0   935.3500   
24 2021-01-01  11974.1100   86.0    0    0     8.0  11.0   4.0  1332.1100   
25 2021-02-01  15853.3300   86.0    0    0     8.0  25.0   2.0  1692.1200   
26 2021-03-01  16855.0500   86.0    0    0     8.0  27.0   8.0  2562.1800   
27 2021-04-01  20098.1500   86.0    0    0     8.0  40.0   5.0  2794.9800   
28 2021-05-01  16709.0300   86.0    0    0     8.0  39.0  10.0  2474.5600   
29 2021-06-01  16196.5800   86.0    0    0     8.0  37.0   7.0  1236.8600   
30 2021-07-01  19456.5400   86.0  399    0     8.0  34.0  11.0   859.4000   
31 2021-08-01  16648.9600   86.0  493    0     2.0  36.0   0.0  1458.7400   
32 2021-09-01  19808.2500   86.0  422   22   583.0  24.0   5.0   953.3000   
33 2021-10-01  16802.9500   86.0  456  116  1053.0  42.0  13.0  1513.8900   
34 2021-11-01  17094.6000   86.0  377  101   161.0  27.0   3.0  1492.2200   
35 2021-12-01  17866.4100   86.0  240   95    35.0  17.0   0.0   253.5000   
36 2022-01-01  12159.9600   86.0  360   76  1648.0   2.0   2.0   655.7300   
37 2022-02-01  16655.8400   86.0  345   74    73.0  17.0   1.0   678.3000   
38 2022-03-01  20452.8900   86.0  383   75   758.0  30.0   2.0  1025.8500   
39 2022-04-01  16813.9200   86.0  399  110  1779.0  44.0  13.0  1901.8400   
40 2022-05-01  17278.7300   86.0  461  104    54.0  48.0   5.0  1679.5100   
41 2022-06-01  20899.0500   86.0  385  100   822.0  57.0  10.0  1279.3000   
42 2022-07-01  15835.3900   86.0  324   93  1276.0  35.0   8.0   354.5104   
43 2022-08-01  16921.8000  157.0  336   76    63.0  27.0   3.0   840.5500   
44 2022-09-01  20736.5333  123.0  359   73   594.0  52.0   0.0   489.6833   
45 2022-10-01  17671.0668  181.0  458   89  1110.0  28.0   0.0   496.3500   
46 2022-11-01  17414.1334  152.0  426   85    74.0  23.0   0.0   527.9500   
47 2022-12-01  18302.5333   62.0  142   57    20.0   5.0   0.0    54.7500   
48 2023-01-01  12374.6166  105.0  335   98  1280.0   2.0   1.0   153.1167   
49 2023-02-01  16883.7167  103.0  149   45    80.0   5.0   0.0   216.0333   

          MPBRH  ...  RCTS  RTTS        AV        OTH       NHR   MTV   ENG  \
0

In [ ]:

# df.to_excel("Output_backward_replace.xlsx")

## Process indicators (separate responses):

In [12]:
# Prediction for "TR":

Y = df.iloc[:,[25]]
X = df.iloc[:,1:24]
Y = np.array(Y).astype("int")
X = np.array(X)

In [21]:
# Y

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=47) # 80% training and 20% test

print(y_train.shape)
y_train = y_train.reshape((len(y_train),))
print(y_train.shape)
y_test = y_test.reshape((len(y_test),))

(40, 1)
(40,)


In [15]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

X, y = make_regression(n_features=22)
regr = RandomForestRegressor(max_depth=8, random_state=0,n_estimators=400)
regr.fit(X_train, y_train)
# regr.predict()
y_pred = regr.predict(X_test)
y_pred.shape
y_pred = y_pred.reshape(-1,1)
y_pred.shape

y_test = y_test.reshape(-1,1)
y_test.shape

(10, 1)

In [16]:
y_pred

array([[1140559.10102579],
       [1126583.73579762],
       [ 963428.0868631 ],
       [ 931110.33100397],
       [1125409.66344643],
       [1093336.19197817],
       [1165536.44037103],
       [1038789.23727381],
       [ 708282.18281944],
       [1100843.18329167]])

In [17]:
ss = regr.score(X_test, y_test, sample_weight=None)
ss

0.4607668163745531

In [18]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.4607668163745531

## People Indicators

In [69]:
# Prediction for "TR":

Y = df.iloc[:,[36]]
X = df.iloc[:,26:35]
Y = np.array(Y)
X = np.array(X)

In [70]:
Y

array([[0.04      ],
       [0.04      ],
       [0.09      ],
       [0.04      ],
       [0.1       ],
       [0.11      ],
       [0.03      ],
       [0.01      ],
       [0.03      ],
       [0.08      ],
       [0.05      ],
       [0.05      ],
       [0.03      ],
       [0.11      ],
       [0.1       ],
       [0.05      ],
       [0.03      ],
       [0.03      ],
       [0.12      ],
       [0.02      ],
       [0.09      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.02752294],
       [0.04464286],
       [0.1       ],
       [0.05357143],
       [0.03968254],
       [0.00813008],
       [0.04166667],
       [0.0483871 ],
       [0.09243697],
       [0.03225806],
       [0.04032258],
       [0.02439024],
       [0.04166667],
       [0.04201681],
       [0.06956522],
       [0.02419355],
       [0.048     ],
       [0.05737705],
       [0.09166667],
       [0.04132231],
       [0.04761905],
       [0.08064516],
       [0.03278689],
       [0.024

In [71]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=47) # 80% training and 20% test

print(y_train.shape)
y_train = y_train.reshape((len(y_train),))
print(y_train.shape)
y_test = y_test.reshape((len(y_test),))

(40, 1)
(40,)


In [72]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

X, y = make_regression(n_features=9)
regr = RandomForestRegressor(max_depth=8, random_state=0,n_estimators=100)
regr.fit(X_train, y_train)
# regr.predict()
y_pred = regr.predict(X_test)
y_pred.shape
y_pred = y_pred.reshape(-1,1)
y_pred.shape

y_test = y_test.reshape(-1,1)
y_test.shape

(10, 1)

In [73]:
y_pred

array([[0.06083309],
       [0.04855884],
       [0.08509998],
       [0.04639973],
       [0.06777569],
       [0.05929931],
       [0.08553459],
       [0.05528025],
       [0.04531912],
       [0.03802246]])

In [74]:
ss = regr.score(X_test, y_test, sample_weight=None)
ss

-0.2926726042532328