In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats
from scipy.stats import norm
from scipy.stats import bootstrap

In [17]:
df = pd.read_excel("Data_Predictive_Models.xlsx", sheet_name = "Compiled_Data (2)")
# df

# df = df.drop(["Dates"], axis = 1)
heads = df.columns.to_list()
# heads

In [18]:
df = df.fillna(method="bfill")

In [19]:
# df.head(100)

In [20]:

# df.to_excel("Output_backward_replace.xlsx")

In [58]:
X1 = df.iloc[:,1]
X1 = np.array(X1)

In [59]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit(X1)

NotFittedError: This OneHotEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

## Process indicators (separate responses):

In [45]:
# Prediction for "TR":

Y = df.iloc[:,[25]]
X = df.iloc[:,1:25]



In [46]:
Y = np.array(Y)
X = np.array(X)


array([[1071257.64923423],
       [1141260.42653196],
       [1549263.89191892],
       [1400876.21255063],
       [1328409.03422998],
       [1545815.76855955],
       [1196442.90257809],
       [1060181.66661404],
       [1072771.63760977],
       [1179441.87343452],
       [ 989598.58432519],
       [ 992311.49329051],
       [ 835703.18083115],
       [1214996.66528135],
       [1138479.81196716],
       [ 400664.89005864],
       [1063498.01204559],
       [1262001.9901208 ],
       [1284330.38313016],
       [1505487.05498091],
       [1353981.0495387 ],
       [1477237.82395379],
       [1132751.51047588],
       [ 941588.2888534 ],
       [1249500.16038369],
       [1192354.45986051],
       [1527448.43068254],
       [1397490.44098772],
       [1821182.2383284 ],
       [1377637.30318929],
       [1499811.0174636 ],
       [1355621.40308024],
       [1234190.91452668],
       [1913573.74752544],
       [1489595.75409276],
       [1155759.67519524],
       [1586400.40504161],
 

In [52]:
X

array([[1.00000000e+00, 1.60768300e+04, 8.60000000e+01, ...,
        3.26690000e+03, 2.36120000e+03, 1.22372000e+03],
       [2.00000000e+00, 1.63459000e+04, 8.60000000e+01, ...,
        3.26690000e+03, 2.36120000e+03, 1.22372000e+03],
       [3.00000000e+00, 1.76584200e+04, 8.60000000e+01, ...,
        3.26690000e+03, 2.36120000e+03, 1.22372000e+03],
       ...,
       [1.20000000e+01, 1.83025333e+04, 6.20000000e+01, ...,
        2.24565933e+03, 0.00000000e+00, 1.63023000e+03],
       [1.00000000e+00, 1.23746166e+04, 1.05000000e+02, ...,
        2.54100000e+03, 0.00000000e+00, 4.58706000e+03],
       [2.00000000e+00, 1.68837167e+04, 1.03000000e+02, ...,
        3.59000000e+03, 0.00000000e+00, 2.56320000e+03]])

In [47]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=47) # 80% training and 20% test

print(y_train.shape)
y_train = y_train.reshape((len(y_train),))
print(y_train.shape)
y_test = y_test.reshape((len(y_test),))

(40, 1)
(40,)


In [48]:
from sklearn.ensemble import RandomForestRegressor

regr = RandomForestRegressor(max_depth=14, n_estimators=400)
regr.fit(X_train, y_train)
# regr.predict()
y_pred = regr.predict(X_test)
y_pred.shape
y_pred = y_pred.reshape(-1,1)
y_pred.shape

y_test = y_test.reshape(-1,1)
y_test.shape

(10, 1)

In [49]:
y_pred

array([[1709807.97463458],
       [1598827.71592023],
       [1509053.05067037],
       [1265812.37177099],
       [1784708.80172375],
       [1527491.33227856],
       [1579332.42236333],
       [1419925.79659772],
       [1066654.43000305],
       [1493723.84221888]])

In [50]:
ss = regr.score(X_test, y_test, sample_weight=None)
ss

0.4999822005137744

In [51]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.4999822005137744

## People Indicators

In [ ]:
# Prediction for "TR":

Y = df.iloc[:,[37]]
X = df.iloc[:,26:35]
Y = np.array(Y)
X = np.array(X)

In [ ]:
Y = np.flip(Y, 0)
Y

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=47) # 80% training and 20% test

print(y_train.shape)
y_train = y_train.reshape((len(y_train),))
print(y_train.shape)
y_test = y_test.reshape((len(y_test),))

In [ ]:
from sklearn.ensemble import RandomForestRegressor

regr = RandomForestRegressor(max_depth=14, random_state=0,n_estimators=400)
regr.fit(X_train, y_train)
# regr.predict()
y_pred = regr.predict(X_test)
y_pred.shape
y_pred = y_pred.reshape(-1,1)
y_pred.shape

y_test = y_test.reshape(-1,1)
y_test.shape

In [ ]:
y_pred

In [ ]:
ss = regr.score(X_test, y_test, sample_weight=None)
ss