In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats
from scipy.stats import norm
from scipy.stats import bootstrap

In [2]:
df = pd.read_excel("Data_Predictive_Models.xlsx", sheet_name = "Data_Predictive_Models")
# df

# df = df.drop(["Dates"], axis = 1)
heads = df.columns.to_list()
# heads

In [3]:
df = df.fillna(method="backfill")

In [4]:
# df.head(100)

In [5]:

# df.to_excel("Output_backward_replace.xlsx")

## Process indicators (separate responses):

In [15]:
# Prediction for "TR":

Y = df.iloc[:,[25]]
X = df.iloc[:,1:24]
Y = np.array(Y).astype("int")
X = np.array(X)

In [16]:
X

array([[16076.83      ,    69.        ,   216.        , ...,
         4037.87403552,  2054.244     ,  1395.0408    ],
       [16345.9       ,   181.        ,   242.        , ...,
         5037.07291666,  2514.0025    ,  3455.01      ],
       [17658.42      ,   116.        ,   378.        , ...,
         5419.65978402,   771.6345    ,  7817.8077    ],
       ...,
       [18302.5333    ,    62.        ,   142.        , ...,
         2245.659327  ,     0.        ,  1630.23      ],
       [12374.6166    ,   105.        ,   335.        , ...,
         2541.        ,     0.        ,  4587.06      ],
       [16883.7167    ,   103.        ,   149.        , ...,
         3590.        ,     0.        ,  2563.2       ]])

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=47) # 80% training and 20% test

print(y_train.shape)
y_train = y_train.reshape((len(y_train),))
print(y_train.shape)
y_test = y_test.reshape((len(y_test),))

(40, 1)
(40,)


In [18]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

# X, y = make_regression(n_features=9)
regr = RandomForestRegressor(max_depth=25, random_state=0,n_estimators=800)
regr.fit(X_train, y_train)
# regr.predict()
y_pred = regr.predict(X_test)
y_pred.shape
y_pred = y_pred.reshape(-1,1)
y_pred.shape

y_test = y_test.reshape(-1,1)
y_test.shape

(10, 1)

In [19]:
y_pred

array([[1170370.17375],
       [1076729.74375],
       [ 991946.98625],
       [1024356.79125],
       [1047321.405  ],
       [1191783.2525 ],
       [1260546.085  ],
       [ 982451.14125],
       [ 743472.1975 ],
       [1134001.35625]])

In [20]:
ss = regr.score(X_test, y_test, sample_weight=None)
ss

0.19912595069176953

In [21]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.19912595069176953

## People Indicators

In [53]:
# Prediction for "TR":

Y = df.iloc[:,[37]]
X = df.iloc[:,26:35]
Y = np.array(Y)
X = np.array(X)

In [55]:
Y = np.flip(Y, 0)
Y

array([[ 9.61174242],
       [13.02083333],
       [ 5.53977273],
       [ 8.80681818],
       [ 9.375     ],
       [ 7.8125    ],
       [12.04710145],
       [ 7.60416667],
       [ 6.91287879],
       [ 7.29166667],
       [ 9.32539683],
       [10.59782609],
       [ 8.48958333],
       [12.79761905],
       [ 8.65559327],
       [ 9.86585479],
       [10.03256989],
       [ 8.45788913],
       [ 6.89542365],
       [ 7.54896571],
       [ 7.        ],
       [ 6.        ],
       [ 8.        ],
       [ 8.        ],
       [10.        ],
       [ 9.        ],
       [11.        ],
       [ 5.        ],
       [ 6.        ],
       [11.        ],
       [10.        ],
       [ 6.        ],
       [ 9.        ],
       [ 7.        ],
       [ 7.        ],
       [ 5.        ],
       [ 7.        ],
       [12.        ],
       [11.        ],
       [ 8.        ],
       [ 6.        ],
       [11.        ],
       [10.        ],
       [11.        ],
       [ 7.        ],
       [ 5

In [56]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=47) # 80% training and 20% test

print(y_train.shape)
y_train = y_train.reshape((len(y_train),))
print(y_train.shape)
y_test = y_test.reshape((len(y_test),))

(40, 1)
(40,)


In [57]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

X, y = make_regression(n_features=9)
regr = RandomForestRegressor(max_depth=14, random_state=0,n_estimators=400)
regr.fit(X_train, y_train)
# regr.predict()
y_pred = regr.predict(X_test)
y_pred.shape
y_pred = y_pred.reshape(-1,1)
y_pred.shape

y_test = y_test.reshape(-1,1)
y_test.shape

(10, 1)

In [58]:
y_pred

array([[7.53610595],
       [9.71007053],
       [8.8317384 ],
       [9.51571606],
       [7.06463827],
       [8.72160368],
       [7.35219868],
       [7.31787164],
       [7.25315087],
       [9.46963645]])

In [59]:
ss = regr.score(X_test, y_test, sample_weight=None)
ss

0.4896181686133717