In [1]:
# Bootstrapping_data

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats
from scipy.stats import norm
from scipy.stats import bootstrap

In [2]:
df = pd.read_excel("Data_Treatment - Great_Lakes.xlsx", sheet_name = "Compiled_Data")
# df

# df = df.drop(["Dates"], axis = 1)
heads = df.columns.to_list()
# heads

In [3]:
df = df.fillna(method="bfill")

In [4]:
# df.head(100)

In [ ]:

# df.to_excel("Output_backward_replace.xlsx")

In [5]:
# data = pd.read_csv('data.csv')
Y = df.iloc[:,[23,24]]
X = df.iloc[:,1:23]
Y = np.array(Y)
X = np.array(X)

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=109) # 80% training and 20% test


In [9]:
print(y_train.shape)


(40, 2)


In [11]:
# y_train = y_train.reshape((len(y_train),))


In [ ]:
# print(y_train.shape)
# y_test = y_test.reshape((len(y_test),))

In [12]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
X, y = make_regression(n_features=22)
regr = RandomForestRegressor(max_depth=9, random_state=0, n_estimators=400)
regr.fit(X_train, y_train)
# regr.predict()
y_pred = regr.predict(X_test)
# y_pred.shape
# y_pred = y_pred.reshape(-1,1)
# y_pred.shape

# y_test = y_test.reshape(-1,1)
# y_test.shape

In [13]:
y_pred

array([[   6510.56650958, 1168902.69864224],
       [   9643.747575  , 1500535.60765698],
       [   7397.14135958, 1410108.76747392],
       [   7217.9646394 , 1539998.54040294],
       [   5250.7531    , 1460147.38815328],
       [   6899.05066125, 1237269.47782456],
       [   7787.58618125, 1380989.25916048],
       [   4599.06935   , 1413924.45292685],
       [   6000.5071    , 1215051.97926919],
       [   9832.1237    , 1726207.40154512]])

In [14]:
ss = regr.score(X_test, y_test, sample_weight=None)
ss

c:\Users\User\PycharmProjects\IE610\ven610\lib\site-packages\sklearn\base.py:434: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


0.5953111221480839

In [15]:
aa = regr.score(X_train, y_train, sample_weight=None)
aa

c:\Users\User\PycharmProjects\IE610\ven610\lib\site-packages\sklearn\base.py:434: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


0.9524863085304145

## separate responses:

In [62]:
# Prediction for "TR":

Y = df.iloc[:,[24]]
X = df.iloc[:,1:24]
Y = np.array(Y).astype("int")
X = np.array(X)

In [67]:
X[:,-1]

array([ 1223.72,  1223.72,  1223.72,  1223.72,  1223.72,  1223.72,
        1223.72,  1223.72,  1223.72,  1223.72,  1223.72,  1223.72,
        1223.72,  3838.9 ,  7043.07,  6856.86,  5027.31, 10184.28,
        9627.24, 11313.11,  6122.36,  5694.75,  6861.99,  4488.13,
        1855.2 , 10471.17, 14027.96, 15606.45,  6561.28,  7060.72,
       13171.34, 14413.59,  4739.22, 22139.55,  9028.7 ,  6288.36,
         246.31,  7180.04,  8446.36, 19370.96, 18349.97, 19943.08,
        9522.85,  8199.07, 15401.41,  6570.72,  6676.76,  1630.23,
        4587.06,  2563.2 ])

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=109) # 80% training and 20% test

print(y_train.shape)
y_train = y_train.reshape((len(y_train),))
print(y_train.shape)
y_test = y_test.reshape((len(y_test),))

(40, 1)
(40,)


In [59]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

X, y = make_regression(n_features=22)
regr = RandomForestRegressor(max_depth=8, random_state=0,n_estimators=400)
regr.fit(X_train, y_train)
# regr.predict()
y_pred = regr.predict(X_test)
y_pred.shape
y_pred = y_pred.reshape(-1,1)
y_pred.shape

y_test = y_test.reshape(-1,1)
y_test.shape

(10, 1)

In [60]:
y_pred

array([[1164859.73576786],
       [1488896.42066667],
       [1414562.3087619 ],
       [1541550.9155625 ],
       [1443568.75164286],
       [1252328.82395536],
       [1431103.10254167],
       [1423978.42116667],
       [1206788.78266667],
       [1702844.34708333]])

In [68]:
ss = regr.score(X_test, y_test, sample_weight=None)
ss

0.5822436622425254

In [55]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.5947184742976228