In [232]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats
from scipy.stats import norm
from scipy.stats import bootstrap

In [257]:
df = pd.read_excel("Data_Predictive_Models.xlsx", sheet_name = "Compiled_Data (2)")
# df

# df = df.drop(["Dates"], axis = 1)
heads = df.columns.to_list()
# heads

In [258]:
df = df.fillna(method="bfill")

In [259]:
X1 = df.iloc[:,[1]]
X1 = np.array(X1)
X1

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [ 1],
       [ 2]], dtype=int64)

In [260]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(categories='auto')
enc.fit(X1)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [261]:
X_enc = enc.transform(X1).toarray()
X_tr = X_enc.transpose()
X_tr.shape


(12, 50)

In [262]:
enc_dict = {}
for i in range(12):
    enc_dict[i] = X_tr[i]

for i in range(12):
    df = pd.concat([df, pd.DataFrame(enc_dict[i], columns=[i])], axis=1)


In [263]:
enc_dict

{0: array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]),
 1: array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),
 2: array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 3: array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 4: array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
     

In [264]:
heads_new = [0,1,2,3,4,5,6,7,8,9,10,11]
for i in heads:
    heads_new.append(i)

heads_new

df = df[heads_new]
df = df.drop(["Month"], axis = 1)
df = df.drop(["DATE"], axis = 1)

In [265]:
df

0    1    2    3    4    5    6    7    8    9  ...  RCTS  RTTS  \
0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   290  1370   
1   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   340  1550   
2   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   600  2490   
3   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...     0  2030   
4   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...     0  2070   
5   0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...     0  1640   
6   0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...     0  1335   
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...     0  1675   
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...     0  1265   
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...     0  1680   
10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...     0  1260   
11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...     0   965   
12  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...     0  1195   
13  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...     0  1095   
14  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...     0  1200   
15  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...     0  1105   
16  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...     0   695   
17  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...     0  1345   
18  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...     0  1880   
19  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...     0  1525   
20  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...     0  1500   
21  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...     0  1758   
22  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...     0     0   
23  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...     0     0   
24  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...     0     0   
25  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...     0     0   
26  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...     0     0   
27  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...     0     0   
28  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...     0     0   
29  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...     0     0   
30  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...     0  1995   
31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...     0  2465   
32  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...   504  2220   
33  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...   580  2860   
34  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   505  2390   
35  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   475  1675   
36  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   380  2180   
37  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   370  2095   
38  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   375  2290   
39  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   550  2545   
40  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   520  2825   
41  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   500  2425   
42  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...   465  2085   
43  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...   380  2060   
44  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...   365  2160   
45  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...   445  2735   
46  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   425  2555   
47  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   285   995   
48  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   490  2165   
49  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   225   970   

          AV        OTH        NHR   MTV  ENG   STL        TNR         AR  
0   5.762570  1732.2600   2.000000  71.0   79  34.0   4.000000  10.000000  
1   5.762570  1732.2600   2.000000  73.0   82  28.0   4.000000   8.000000  
2   5.762570  1732.2600   2.000000  70.0   83  28.0   

In [266]:
df.to_excel("encoded.xlsx")

## Process indicators (separate responses):

In [281]:
# Prediction for "TR":

Y = df.iloc[:,[36]]
X = df.iloc[:,0:35]



In [282]:
Y = np.array(Y)
X = np.array(X)


In [283]:
Y

array([[ 728455.20147928],
       [ 730406.67298045],
       [1332366.94705027],
       [1120700.97004051],
       [ 690772.69779959],
       [1205736.29947645],
       [ 622150.3093406 ],
       [ 710321.71663141],
       [ 740212.42995074],
       [ 601515.35545161],
       [ 742198.9382439 ],
       [ 506078.86157816],
       [ 526493.00392363],
       [ 765447.89912725],
       [ 967707.84017209],
       [ 216359.04063166],
       [ 882703.34999784],
       [1060081.67170147],
       [ 577948.67240857],
       [1264609.12618396],
       [ 853008.06120938],
       [ 842025.55965366],
       [ 826908.60264739],
       [ 969835.937519  ],
       [ 912135.1170801 ],
       [1037348.38007864],
       [1284035.6325    ],
       [1076968.9995    ],
       [1038604.482     ],
       [1076228.652     ],
       [ 817978.992     ],
       [ 983130.1055    ],
       [ 923178.3185    ],
       [1015414.112     ],
       [1106287.328     ],
       [ 617158.536     ],
       [1085896.2995    ],
 

In [284]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=47) # 80% training and 20% test

print(y_train.shape)
y_train = y_train.reshape((len(y_train),))
print(y_train.shape)
y_test = y_test.reshape((len(y_test),))

(40, 1)
(40,)


In [285]:
from sklearn.ensemble import RandomForestRegressor

regr = RandomForestRegressor(max_depth=20, n_estimators=800)
regr.fit(X_train, y_train)
# regr.predict()
y_pred = regr.predict(X_test)
y_pred.shape
y_pred = y_pred.reshape(-1,1)
y_pred.shape

y_test = y_test.reshape(-1,1)
y_test.shape

(10, 1)

In [286]:
y_pred

array([[1151811.24876945],
       [1079421.9367982 ],
       [1063126.62786273],
       [ 909140.93186432],
       [1126224.71786982],
       [1068150.52278785],
       [1185353.75109416],
       [1053954.67059282],
       [ 712048.9722844 ],
       [1096460.59091597]])

In [287]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.45176158512610565

In [288]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

38859361683.267624

In [289]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

180514.24062602507

In [290]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.datasets import make_regression

# X, y = make_regression(n_features=22)
# regr = GradientBoostingRegressor(learning_rate=0.1, n_estimators=100, subsample=1.0, 
#                                  criterion='friedman_mse', min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
#                                  max_depth=3, min_impurity_decrease=0.0)

regr = GradientBoostingRegressor(learning_rate=0.05, n_estimators=800, subsample=1.0, 
                                 criterion='friedman_mse', min_samples_split=2, min_samples_leaf=5, min_weight_fraction_leaf=0.0, 
                                 max_depth=24, min_impurity_decrease=0.0)

regr.fit(X_train, y_train)
# regr.predict()
y_pred = regr.predict(X_test)
y_pred.shape
y_pred = y_pred.reshape(-1,1)
y_pred.shape

y_test = y_test.reshape(-1,1)
y_test.shape

(10, 1)

In [291]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.32986507508192864

In [292]:
# !pip install sklearn --upgrade --user

In [293]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)


47499435861.25878

In [294]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)


187329.86814801063

## People Indicators

In [220]:
# Prediction for "TR":
# df = df.drop(["",""], axis = 1)


Y = df.iloc[:,[48]]
X = df.iloc[:,0:46]
Y = np.array(Y).astype("float16")
X = np.array(X)

In [221]:
# Y= np.flip(Y, 0)
Y

array([[10.   ],
       [ 8.   ],
       [ 5.   ],
       [ 6.   ],
       [ 5.   ],
       [ 7.   ],
       [11.   ],
       [10.   ],
       [11.   ],
       [ 6.   ],
       [ 8.   ],
       [11.   ],
       [12.   ],
       [ 7.   ],
       [ 5.   ],
       [ 7.   ],
       [ 7.   ],
       [ 9.   ],
       [ 6.   ],
       [10.   ],
       [11.   ],
       [ 6.   ],
       [ 5.   ],
       [11.   ],
       [ 9.   ],
       [10.   ],
       [ 8.   ],
       [ 8.   ],
       [ 6.   ],
       [ 7.   ],
       [ 7.55 ],
       [ 6.895],
       [ 8.46 ],
       [10.03 ],
       [ 9.87 ],
       [ 8.66 ],
       [12.8  ],
       [ 8.49 ],
       [10.6  ],
       [ 9.33 ],
       [ 7.293],
       [ 6.914],
       [ 7.605],
       [12.05 ],
       [ 7.812],
       [ 9.375],
       [ 8.805],
       [ 5.54 ],
       [13.02 ],
       [ 9.61 ]], dtype=float16)

In [222]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=47) # 80% training and 20% test

print(y_train.shape)
y_train = y_train.reshape((len(y_train),))
print(y_train.shape)
y_test = y_test.reshape((len(y_test),))

(40, 1)
(40,)


In [223]:
from sklearn.ensemble import RandomForestRegressor

regr = RandomForestRegressor(max_depth=24, random_state=0,n_estimators=800)
regr.fit(X_train, y_train)
# regr.predict()
y_pred = regr.predict(X_test)
y_pred.shape
y_pred = y_pred.reshape(-1,1)
y_pred.shape

y_test = y_test.reshape(-1,1)
y_test.shape

(10, 1)

In [224]:
y_pred

array([[8.43605469],
       [7.5280957 ],
       [6.88898437],
       [9.83194336],
       [7.8131543 ],
       [8.90674805],
       [8.08326172],
       [7.75039062],
       [8.1315918 ],
       [8.61258789]])

In [225]:
ss = regr.score(X_test, y_test, sample_weight=None)
ss

-0.4014402279498306

In [226]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)


3.5393379799842832

In [227]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)


1.5423222656250002

In [228]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.datasets import make_regression

# X, y = make_regression(n_features=22)
# regr = GradientBoostingRegressor(learning_rate=0.1, n_estimators=100, subsample=1.0, 
#                                  criterion='friedman_mse', min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
#                                  max_depth=3, min_impurity_decrease=0.0)

regr = GradientBoostingRegressor(learning_rate=0.1, n_estimators=400, subsample=1.0, 
                                 criterion='friedman_mse', min_samples_split=2, min_samples_leaf=5, min_weight_fraction_leaf=0.0, 
                                 max_depth=14, min_impurity_decrease=0.0)

regr.fit(X_train, y_train)
# regr.predict()
y_pred = regr.predict(X_test)
y_pred.shape
y_pred = y_pred.reshape(-1,1)
y_pred.shape

y_test = y_test.reshape(-1,1)
y_test.shape

(10, 1)

In [229]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-0.6774136372086725

In [230]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)


4.23630895982013

In [231]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)


1.701958120439754